map_type: costmap

footprint: [[-0.25, -0.20], [-0.25, 0.20], [0.25, 0.20], [0.25, -0.20]]
footprint_padding: 0.01

robot_base_frame: base_footprint
publish_frequency: 3.0
transform_tolerance: 1.0

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

inflation:
    inflation_radius: 1.0
